global proc Split (string $Stringtosplit)
{
    string $store[];
    string $number;
    string $SelectedObj[] = `ls -selection`;
    int $numRange = 1;

    tokenize $Stringtosplit "#" $store;

    

    for ($iterate in $SelectedObj)
    {
         $number = "0"+$numRange; 

         string $fullString= $store[0]+"_"+$number+"_"+$store[1];
         rename $iterate $fullString;
         $numRange++;
    }
     
}
Split("arm_##_jnt");